// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxZjRg4rrm0B2R1BhhZn9lBqzFro4Zx_Y',
    appId: '1:586003730249:web:56203f05c7e19a98c95498',
    messagingSenderId: '586003730249',
    projectId: 'flutter-projet-a29ae',
    authDomain: 'flutter-projet-a29ae.firebaseapp.com',
    storageBucket: 'flutter-projet-a29ae.appspot.com',
    measurementId: 'G-24QR5VD0LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi1CZBx6VG76HFISbjc4NxiNx_5ZOvDxA',
    appId: '1:586003730249:android:45a7b11b77e82151c95498',
    messagingSenderId: '586003730249',
    projectId: 'flutter-projet-a29ae',
    storageBucket: 'flutter-projet-a29ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkE_JVYtEnt0X7LQHIus-UfNMI71-sL84',
    appId: '1:586003730249:ios:122f3c41addf2c82c95498',
    messagingSenderId: '586003730249',
    projectId: 'flutter-projet-a29ae',
    storageBucket: 'flutter-projet-a29ae.appspot.com',
    androidClientId: '586003730249-bhalq17s3o4huvld53b0s80cd47r2fog.apps.googleusercontent.com',
    iosClientId: '586003730249-u886gsr8h3sii4jbq97b2ki7ij11pqb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoTasksWithAlert',
  );
}
